export default function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-6xl my-8">
      <div className="border-b-2 text-center"><h4 className="pl-3 text-xl sm:text-3xl">Privacy Policy</h4></div>
      <div className="p-5 bg-[#F8F8F8]">
        <div className=" border-2 p-6 bg-white">
          <div><p className="text-xs xl:text-sm text-light">** This form is provided as a sample to help with the operation of the shopping mall and needs to be modified according to the type of shopping mall operation.efore applying to the shopping mall, please check the shopping mall operation details and reflect the appropriate contents before use.**</p>

            <p className="text-xs xl:text-sm text-light"><span>Irepharm Co., Ltd.</span> (hereinafter referred to as the "Company") values ​​the personal information of customers and complies with the Act on Promotion of Information and Communications Network Utilization and Information Protection. <br />Through the personal information processing policy, the company informs you of the purpose and method of using the personal information provided by customers and what measures are being taken to protect personal information.</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Collected personal information items and collection methods</h6> <br />A.tems of personal information collected <br />o The company collects the following personal information for membership registration, consultation, service application, etc. <br />- When signing up for membership: Name, date of birth, gender, login ID, password, home phone number, mobile phone number, e-mail, information of legal representative for subscribers under the age of 14 - When applying for service: address, payment <br />information</p>

            <p className="text-xs xl:text-sm text-light">o Service use records, access logs, cookies, access IPs, payment records, and bad use records may be created and collected during service use or business processing.</p>

            <p className="text-xs xl:text-sm text-light">me.ollection method <br />- Collection through website, written form, bulletin board, e-mail, event application, delivery request, telephone, fax, and generated information collection tool</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Purpose of collection and use of personal information</h6> <br />The company uses the collected personal information for the following purposes. <br />o Implementation of contracts related to service provision <br />, provision of contents for fee settlement according to service provision, purchase and payment, delivery of goods or billing address, authentication of financial transaction and <br />financial <br />service , Prevention of fraudulent use of bad members and prevention of unauthorized use, Confirmation of intention to sign up, age confirmation, confirmation of consent of legal representative when collecting personal informationfhildren under 14 years of age, handling complaints, etc., delivery of notices o Events used for marketing and <br />advertising <br />Delivery of advertising information, etc., identification of access frequency, or statistics on service use by members</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Retention and use period of personal information</h6> <br />In principle, after the purpose of collecting and using personal information is achieved, the information is destroyed without delay.owever, the following information is retained for the specified period for the following reasons.</p>

            <p className="text-xs xl:text-sm text-light">go.easons for information retention according to company internal policy <br />&nbsp;Even if a member withdraws, the member's information can be retained for oo years from the date of termination of the use contract in order to prevent the recurrence of fraudulent use by bad members, resolve disputes, and cooperate with the request of investigative agencies. there is.</p>

            <p className="text-xs xl:text-sm text-light">me.easons for retaining information according to related laws <br />If it is necessary to preserve it according to the provisions of related laws, such as the Consumer Protection Act in Electronic Commerce, etc. <br />o Records on contracts or withdrawal of subscription <br />- Reason for retention: Consumer Protection Act in Electronic Commerce, etc. <br />- Retention period: 5 years <br />o Records on payment and supply of goods, etc. <br />- Reason for retention: Consumer protection in electronic commerce, etc. Law <br />- Retention period: 5 years <br />o Records on handling consumer complaints or disputes <br />- Retention reason: Consumer Protection Act in Electronic Commerce, etc. <br />- Retention period: 3 text-sm sm:text-base lg:text-lg years <br />o Log records <br />- Retention reason: Protection of Communications Secrets Act <br />- Retention period: 3 text-sm sm:text-base lg:text-lg month</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Destruction procedure and method of personal information </h6><br />In principle, the company destroys the information without delay after the purpose of collecting and using personal information is achieved.he destruction procedure and method are as follows. <br />o Destruction procedure <br />The information entered by the member for membership registration, etc., is transferred to a separate DB after the purpose is achieved (separate filing cabinet in case of paper), Reference After being stored for a certain period of time, it is destroyed. <br />Personal information transferred to a separate DB is not used for any purpose other than being retained unless otherwise required by law. <br />o Destruction method <br />Personal information stored in the form of an electronic file is deleted using a technical method that cannot reproduce the record.</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Personal Information Provision</h6> <br />The company does not provide users' personal information to the outside in principle.owever, the following cases are exceptions. <br />o When users agree in advance <br />o In accordance with the provisions of the law, or when there is a request from an investigative agency in accordance with the procedures and methods set forth in the law for the purpose of investigation</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Consignment of collected personal information</h6> <br />The company entrusts the service to an external professional company as follows. <br />o Entrusted person: [Name of courier company] <br />o Details of consignment service: [Consignment details of courier company]</p>

            <p className="text-xs xl:text-sm text-light">o Entrusted person: [PG company name] <br />o Details of consignment work: [PG company consignment details]</p>

            <p className="text-xs xl:text-sm text-light">o Entrusted person: <a href="/protected/supply/list.html" target="_blank">View list of suppliers</a><br /> o Details of consignment task: [Details of entrusted task]</p>

            <p className="text-xs xl:text-sm text-light"><br /><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Rights of users and legal representatives and how to exercise them</h6> <br />o Users can view or modify their registered personal information at any time, and may request cancellation of membership. <br />o To view or modify personal information of users, click "Change personal information" (or "Edit member information", etc.), or click "Withdraw membership" to cancel subscription (withdrawal of consent). Correction or withdrawal is possible. <br />o Or, if you contact the person in charge of personal information protection in writing, by phone or e-mail, we will take action without delay. <br />o If you request correction of an error in personal information, the personal information will not be used or provided until the correction is completed.n addition, if wrong personal information has already been provided to a third party, the result of the correction will be notified to the third party without delay so that the correction can be made. <br />o The company handles personal information that has been terminated or deleted at the user's request as specified in "Retention and use period of personal information collected by the company" and makes sure that it is not viewed or used for any other purpose.</p>

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Matters concerning the installation, operation and refusal of automatic personal information collection devices</h6> <br />The company operates "cookies" that frequently store and find your information. cookie is a very small text file sent to your browser by the server used to run the website and stored on your computer's hard disk. <br />The company uses cookies for the following purposes. Purpose of use, such as <br />cookies. You have a choice about installing cookies.herefore, you can allow all cookies by setting options in your web browser, go through confirmation whenever a cookie is saved, or refuse to save all cookies. Method of rejecting cookie setting. To reject cookie setting, you can allow all cookies by selecting the option of the web browser you are using, go through confirmation every time a cookie is saved, or refuse to save all cookies. .. Example of setting method (in case of Internet Explorer): Tools at the top of the web browser &gt; Internet Options &gt; Personal Information. However, if you refuse to install cookies, there may be difficulties in providing services.</p><br /><br /><br />

            <p className="text-xs xl:text-sm text-light"><h6 className="mb-0 border-l-2 border-secondary pl-3 text-sm sm:text-base lg:text-lg">Complaint service related to personal information </h6><br />The company has designated the relevant department and personal information manager as follows to protect customers' personal information and handle complaints related to personal information. <br />o Personal Information Manager <br />Name: OOO <br />Affiliation: OOO <br />Phone Number: OO-OOO-OOOO <br />Email:</p>

            <p className="text-xs xl:text-sm text-light">o Personal Information Manager <br />Name: OOO <br />Affiliation: OOO <br />Phone Number: OO-OOO-OOOO <br />Email:</p>

            <p className="text-xs xl:text-sm text-light">o You can report all personal information protection-related complaints that occur while using the company's services to the person in charge of personal information protection or the department in charge. <br />o The company will provide prompt and sufficient answers to users' reports. <br />o If you need to report or consult about other personal information infringement, please contact the following organizations. <br />Personal Information Infringement Report Center (privacy.kisa.or.kr / 118 without area code) <br />Personal Information Dispute Mediation Committee (kopico.go.kr / 1833-6972) <br />Cyber ​​Investigation Division of Supreme Prosecutor’s Office (spo.go.kr / area code +1301) <br />National Police Agency Cyber ​​Security Bureau (cyberbureau.police.go.kr / 182 without area code)</p>
          </div>    </div>
      </div>

    </div>

  )
}
