/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AdminUser: { // root type
    created_at?: string | null; // String
    email: string; // String!
    full_name: string; // String!
    id: number; // Int!
    password: string; // String!
    status: boolean; // Boolean!
    updated_at?: string | null; // String
    uuid: string; // String!
  }
  Collection: { // root type
    code: string; // String!
    collection_id: number; // Int!
    created_at?: string | null; // String
    description?: string | null; // String
    name: string; // String!
    updated_at?: string | null; // String
    uuid: string; // String!
  }
  Link: { // root type
    description: string; // String!
    id: number; // Int!
    imageUrl: string; // String!
    url: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AdminUser: { // field return type
    created_at: string | null; // String
    email: string; // String!
    full_name: string; // String!
    id: number; // Int!
    password: string; // String!
    status: boolean; // Boolean!
    updated_at: string | null; // String
    uuid: string; // String!
  }
  Collection: { // field return type
    code: string; // String!
    collection_id: number; // Int!
    created_at: string | null; // String
    description: string | null; // String
    name: string; // String!
    updated_at: string | null; // String
    uuid: string; // String!
  }
  Link: { // field return type
    description: string; // String!
    id: number; // Int!
    imageUrl: string; // String!
    url: string; // String!
  }
  Mutation: { // field return type
    deleteLink: NexusGenRootTypes['Link']; // Link!
    post: NexusGenRootTypes['Link']; // Link!
    updateLink: NexusGenRootTypes['Link']; // Link!
  }
  Query: { // field return type
    feed: NexusGenRootTypes['Link'][]; // [Link!]!
    listAdminUsers: NexusGenRootTypes['AdminUser'][]; // [AdminUser!]!
    listCollection: NexusGenRootTypes['Collection'][]; // [Collection!]!
  }
}

export interface NexusGenFieldTypeNames {
  AdminUser: { // field return type name
    created_at: 'String'
    email: 'String'
    full_name: 'String'
    id: 'Int'
    password: 'String'
    status: 'Boolean'
    updated_at: 'String'
    uuid: 'String'
  }
  Collection: { // field return type name
    code: 'String'
    collection_id: 'Int'
    created_at: 'String'
    description: 'String'
    name: 'String'
    updated_at: 'String'
    uuid: 'String'
  }
  Link: { // field return type name
    description: 'String'
    id: 'Int'
    imageUrl: 'String'
    url: 'String'
  }
  Mutation: { // field return type name
    deleteLink: 'Link'
    post: 'Link'
    updateLink: 'Link'
  }
  Query: { // field return type name
    feed: 'Link'
    listAdminUsers: 'AdminUser'
    listCollection: 'Collection'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    deleteLink: { // args
      id: number; // Int!
    }
    post: { // args
      description: string; // String!
      imageUrl: string; // String!
      url: string; // String!
    }
    updateLink: { // args
      description: string; // String!
      id: number; // Int!
      imageUrl: string; // String!
      url: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}