export const blogDetails = [
  {
    blogLink: "#",
    src: "img/blog/TB-1.png",
    alt: "Blog Image",
    adminLink: "#",
    adminName: "by: Admin",
    tagLink: "#",
    tagName: "corporate",
    blogTitle: "lorem ipsum dolor sit amet lorem ipsum dolor sit amet",
    date: "june 12, 2023",
  },
  {
    blogLink: "#",
    src: "img/blog/TB-2.png",
    alt: "Blog Image",
    adminLink: "#",
    adminName: "by: Admin",
    tagLink: "#",
    tagName: "Corporate",
    blogTitle: "lorem ipsum dolor sit amet lorem ipsum dolor sit amet",
    date: "june 12, 2023",
  },
  {
    blogLink: "#",
    src: "img/blog/TB-3.png",
    alt: "Blog Image",
    adminLink: "#",
    adminName: "by: Admin",
    tagLink: "#",
    tagName: "Corporate",
    blogTitle: "lorem ipsum dolor sit amet lorem ipsum dolor sit amet",
    date: "june 12, 2023",
  },
  {
    blogLink: "#",
    src: "img/blog/TB-4.png",
    alt: "Blog Image",
    adminLink: "#",
    adminName: "by: Admin",
    tagLink: "#",
    tagName: "Corporate",
    blogTitle: "lorem ipsum dolor sit amet lorem ipsum dolor sit amet",
    date: "june 12, 2023",
  },
];
