export const featuredProductDetails = [
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
];
