import { IListProps } from "./Categories/types";

export const featuredProductDetails = [
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
  {
    showStars: true,
    isTextCenter: true,
    isNew: false,
    image: "/placeholder/600x701.png ",
    quickView: "#",
    addToCard: "#",
    wishlist: "#",
    stars: 4,
    productName: "React Product ",
    price: "$124",
    originalPrice: "$156 ",
  },
];

export const listData: IListProps[] = [
  {
    title: "Accessories",
    link: "#",
  },
  {
    title: "Clothing",
    link: "#",
  },
  {
    title: "Decor",
    link: "#",
  },
  {
    title: "Hoodies",
    link: "#",
  },
  {
    title: "Music",
    link: "#",
  },
  {
    title: "Tshirts",
    link: "#",
  },
  {
    title: "Uncategorized",
    link: "#",
  },
];

